# Generated by Django 5.2.17 on 2026-09-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_pymissive', '0014_missiveevent_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='missiverecipient',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Carrier tracking reference for public tracking sites (e.g. La Poste). Distinct from provider external_id.', max_length=255, null=True, verbose_name='Tracking number'),
        ),
    ]
