# Generated by Django 5.2.17 on 2026-09-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_pymissive', '0015_missiverecipient_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='missive',
            name='substitute_id',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='Provider custom_id from another internal reference. When empty, the missive UUID pk is used.',
                max_length=255,
                null=True,
                verbose_name='Substitute ID',
            ),
        ),
        migrations.AddField(
            model_name='missiverecipient',
            name='substitute_id',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='Provider custom_id from another internal reference. When empty, the recipient pk is used.',
                max_length=255,
                null=True,
                verbose_name='Substitute ID',
            ),
        ),
    ]
