# Generated by Django 5.2.17 on 2026-09-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_pymissive', '0016_missive_recipient_substitute_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignrelatedobject',
            name='object_id',
            field=models.CharField(help_text='ID of the related object (integer pk as well as UUID)', max_length=255, verbose_name='Object ID'),
        ),
        migrations.AlterField(
            model_name='missiverecipient',
            name='recipient_support',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('address', 'Address'), ('application', 'Application')], help_text='Model of recipient', max_length=255, verbose_name='Recipient Model'),
        ),
        migrations.AlterField(
            model_name='missiverelatedobject',
            name='object_id',
            field=models.CharField(help_text='ID of the related object (integer pk as well as UUID)', max_length=255, verbose_name='Object ID'),
        ),
        migrations.AlterField(
            model_name='missivescheduledcampaign',
            name='retry_failed',
            field=models.BooleanField(default=False, help_text="If enabled, the campaign's failed missives are archived and duplicated as fresh drafts when this run starts, then sent by it (already archived attempts and conversation messages excluded).", verbose_name='Retry failed'),
        ),
    ]
