# Generated by Django 5.2.17 on 2026-09-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_pymissive', '0017_alter_campaignrelatedobject_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missivebaseattachment',
            name='attachment_object_id',
            field=models.CharField(blank=True, help_text='ID of the object to which this file is attached (integer pk as well as UUID)', max_length=255, null=True, verbose_name='Object ID'),
        ),
    ]
