# Generated by Django 5.2.17 on 2026-09-13 15:40

from django.db import migrations

import django_pymissive.fields


class Migration(migrations.Migration):

    dependencies = [
        ("django_pymissive", "0018_alter_missivebaseattachment_attachment_object_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="missivescheduledcampaign",
            name="campaign_snapshot",
            field=django_pymissive.fields.JSONField(
                blank=True,
                default=dict,
                editable=False,
                help_text="Copy of the campaign configuration captured when this run starts. Later edits to the campaign do not change it.",
                verbose_name="Campaign snapshot",
            ),
        ),
    ]
