# Generated by Django 5.2.17 on 2026-09-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_pymissive', '0019_missivescheduledcampaign_campaign_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missivebaseattachment',
            name='linked',
            field=models.BooleanField(default=True, help_text='If true, the attachment is offered as an access link instead of being physically attached', verbose_name='Linked'),
        ),
    ]
