# Generated by Django 5.2.15 on 2026-09-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_pymissive', '0020_alter_missivebaseattachment_linked'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='campaignrelatedobject',
            index=models.Index(fields=['content_type', 'object_id'], name='django_pymi_content_14b86c_idx'),
        ),
        migrations.AddIndex(
            model_name='missive',
            index=models.Index(fields=['external_id'], name='django_pymi_externa_293827_idx'),
        ),
        migrations.AddIndex(
            model_name='missive',
            index=models.Index(fields=['thread_type', '-created_at'], name='django_pymi_thread__931556_idx'),
        ),
        migrations.AddIndex(
            model_name='missive',
            index=models.Index(fields=['thread_id', 'thread_type'], name='django_pymi_thread__18a93c_idx'),
        ),
        migrations.AddIndex(
            model_name='missive',
            index=models.Index(fields=['campaign', 'thread_type', 'status'], name='django_pymi_campaig_88fa43_idx'),
        ),
        migrations.AddIndex(
            model_name='missivebaseattachment',
            index=models.Index(fields=['attachment_content_type', 'attachment_object_id'], name='django_pymi_attachm_a5ce95_idx'),
        ),
        migrations.AddIndex(
            model_name='missiveevent',
            index=models.Index(fields=['missive', 'recipient', '-occurred_at'], name='django_pymi_missive_c73e93_idx'),
        ),
        migrations.AddIndex(
            model_name='missiverelatedobject',
            index=models.Index(fields=['content_type', 'object_id'], name='django_pymi_content_e0b89d_idx'),
        ),
    ]
