# Generated by Django 5.2.17 on 2026-09-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_pymissive', '0021_missive_lookup_indexes'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='missivebaseattachment',
            constraint=models.UniqueConstraint(condition=models.Q(('missive__isnull', False), ('attachment_type__in', ('attachment', 'virtual_attachment'))), fields=('missive', 'priority'), name='uniq_missive_att_priority'),
        ),
        migrations.AddConstraint(
            model_name='missivebaseattachment',
            constraint=models.UniqueConstraint(condition=models.Q(('campaign__isnull', False), ('attachment_type__in', ('attachment', 'virtual_attachment'))), fields=('campaign', 'priority'), name='uniq_campaign_att_priority'),
        ),
    ]
