# Generated by Django 5.2.17 on 2026-09-16 11:56

import django_pymissive.fields
from django.db import migrations, models

ACKNOWLEDGEMENT_OF_RECEIPT = "acknowledgement_of_receipt"
_LEGACY_POSTAL_TYPES = ("lre", "postal")
_POSTAL_PRODUCTS = ("letter", "registered_letter")


def target_type_for_legacy_postal(missive_type, acknowledgement):
    """Map a stored ``lre`` / ``postal`` value to ``letter`` or ``registered_letter``.

    Until this rename, a single ``lre`` type picked Maileva ``mail/v2`` or
    ``registered_mail/v4`` from ``acknowledgement``. Leftover ``postal`` rows
    (choices dropped in 0003) were always simple mail.
    """
    key = (missive_type or "").strip().lower()
    if key == "postal":
        return "letter"
    if key == "lre":
        ack = (acknowledgement or "").strip().lower()
        if ack == ACKNOWLEDGEMENT_OF_RECEIPT:
            return "registered_letter"
        return "letter"
    return None


def remap_legacy_postal_types(apps, schema_editor):
    Missive = apps.get_model("django_pymissive", "Missive")
    MissiveConfig = apps.get_model("django_pymissive", "MissiveConfig")
    Scheduled = apps.get_model("django_pymissive", "MissiveScheduledCampaign")

    Missive.objects.filter(missive_type="postal").update(missive_type="letter")
    Missive.objects.filter(
        missive_type="lre", acknowledgement=ACKNOWLEDGEMENT_OF_RECEIPT
    ).update(missive_type="registered_letter")
    Missive.objects.filter(missive_type="lre").update(missive_type="letter")

    for sched in Scheduled.objects.filter(missive_type__in=_LEGACY_POSTAL_TYPES).iterator():
        default = "letter" if sched.missive_type == "postal" else "registered_letter"
        targets = set()
        if sched.campaign_id:
            targets = set(
                Missive.objects.filter(
                    campaign_id=sched.campaign_id,
                    missive_type__in=_POSTAL_PRODUCTS,
                )
                .values_list("missive_type", flat=True)
                .distinct()
            )
        if len(targets) == 1:
            new_type = next(iter(targets))
        else:
            new_type = default
        if (
            sched.send_date is None
            and targets == set(_POSTAL_PRODUCTS)
        ):
            Scheduled.objects.create(
                campaign_id=sched.campaign_id,
                scheduled_send_date=sched.scheduled_send_date,
                missive_type="letter",
                retry_failed=sched.retry_failed,
                task_content_type_id=sched.task_content_type_id,
                task_object_id=sched.task_object_id,
                task_object_arguments=sched.task_object_arguments or {},
                external_task_backend=sched.external_task_backend or "",
                additional_config=sched.additional_config or {},
            )
            new_type = "registered_letter"
        if sched.missive_type != new_type:
            sched.missive_type = new_type
            sched.save(update_fields=["missive_type"])

    existing = {
        row.missive_type: row
        for row in MissiveConfig.objects.filter(
            missive_type__in=_LEGACY_POSTAL_TYPES + _POSTAL_PRODUCTS
        )
    }
    postal_cfg = existing.get("postal")
    lre_cfg = existing.get("lre")
    letter_cfg = existing.get("letter")
    registered_cfg = existing.get("registered_letter")

    if postal_cfg is not None:
        if letter_cfg is None:
            postal_cfg.missive_type = "letter"
            postal_cfg.save(update_fields=["missive_type"])
            letter_cfg = postal_cfg
        else:
            postal_cfg.delete()

    if lre_cfg is not None:
        provider = lre_cfg.default_provider
        if registered_cfg is None:
            lre_cfg.missive_type = "registered_letter"
            lre_cfg.save(update_fields=["missive_type"])
        else:
            lre_cfg.delete()
        if letter_cfg is None:
            MissiveConfig.objects.create(
                missive_type="letter",
                default_provider=provider,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('django_pymissive', '0022_missivebaseattachment_uniq_missive_att_priority_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missivecampaign',
            old_name='acknowledgement_lre',
            new_name='acknowledgement_letter',
        ),
        migrations.RenameField(
            model_name='missivecampaign',
            old_name='delivery_mode_lre',
            new_name='delivery_mode_letter',
        ),
        migrations.RenameField(
            model_name='missivecampaign',
            old_name='priority_lre',
            new_name='priority_letter',
        ),
        migrations.AlterField(
            model_name='missive',
            name='body_rich',
            field=django_pymissive.fields.RichTextField(blank=True, help_text='Rich content body (HTML, RTF, …) — email, letter, registered letter, etc.', null=True, verbose_name='Rich body'),
        ),
        migrations.AlterField(
            model_name='missive',
            name='missive_type',
            field=models.CharField(choices=[('letter', 'Simple letter'), ('registered_letter', 'Registered letter'), ('hand_delivery', 'Hand delivery'), ('ere', 'Electronic registered email (ERE)'), ('email', 'Email'), ('email_marketing', 'Marketing email'), ('sms', 'SMS'), ('rcs', 'RCS (Rich SMS)'), ('voice_call', 'Automated voice call'), ('notification', 'In-app notification'), ('push_notification', 'Mobile push notification'), ('branded', 'Branded App messaging (WhatsApp, Slack, etc.)')], help_text='Type of missive (email, sms, letter, registered_letter, ere, etc.)', max_length=50, verbose_name='Missive Type'),
        ),
        migrations.AlterField(
            model_name='missivecampaign',
            name='first_document',
            field=django_pymissive.fields.RichTextField(blank=True, help_text='First document content (HTML, converted to PDF for postal letters)', verbose_name='First Document'),
        ),
        migrations.AlterField(
            model_name='missiveconfig',
            name='missive_type',
            field=models.CharField(choices=[('letter', 'Simple letter'), ('registered_letter', 'Registered letter'), ('hand_delivery', 'Hand delivery'), ('ere', 'Electronic registered email (ERE)'), ('email', 'Email'), ('email_marketing', 'Marketing email'), ('sms', 'SMS'), ('rcs', 'RCS (Rich SMS)'), ('voice_call', 'Automated voice call'), ('notification', 'In-app notification'), ('push_notification', 'Mobile push notification'), ('branded', 'Branded App messaging (WhatsApp, Slack, etc.)')], help_text='Type of missive (email, sms, postal, etc.)', max_length=50, unique=True, verbose_name='Missive type'),
        ),
        migrations.AlterField(
            model_name='missivescheduledcampaign',
            name='missive_type',
            field=models.CharField(choices=[('*', 'All types'), ('letter', 'Simple letter'), ('registered_letter', 'Registered letter'), ('hand_delivery', 'Hand delivery'), ('ere', 'Electronic registered email (ERE)'), ('email', 'Email'), ('email_marketing', 'Marketing email'), ('sms', 'SMS'), ('rcs', 'RCS (Rich SMS)'), ('voice_call', 'Automated voice call'), ('notification', 'In-app notification'), ('push_notification', 'Mobile push notification'), ('branded', 'Branded App messaging (WhatsApp, Slack, etc.)')], default='*', help_text="Restrict sending to missives of this type. '*' sends every type (default).", max_length=50, verbose_name='Missive type'),
        ),
        migrations.RunPython(remap_legacy_postal_types, migrations.RunPython.noop),
    ]
