# Generated by Django 5.2.17 on 2026-09-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_pymissive', '0023_rename_acknowledgement_lre_missivecampaign_acknowledgement_letter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missiveconfig',
            name='missive_type',
            field=models.CharField(choices=[('letter', 'Simple letter'), ('registered_letter', 'Registered letter'), ('hand_delivery', 'Hand delivery'), ('ere', 'Electronic registered email (ERE)'), ('email', 'Email'), ('email_marketing', 'Marketing email'), ('sms', 'SMS'), ('rcs', 'RCS (Rich SMS)'), ('voice_call', 'Automated voice call'), ('notification', 'In-app notification'), ('push_notification', 'Mobile push notification'), ('branded', 'Branded App messaging (WhatsApp, Slack, etc.)')], help_text='Type of missive (email, sms, letter, registered_letter, etc.)', max_length=50, unique=True, verbose_name='Missive type'),
        ),
    ]
