# Generated by Django 5.2.15 on 2026-09-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_pymissive', '0026_missiveevent_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='missive',
            name='color_printing',
            field=models.BooleanField(blank=True, default=None, help_text='Print the letter in color', null=True, verbose_name='Color printing'),
        ),
        migrations.AddField(
            model_name='missive',
            name='duplex_printing',
            field=models.BooleanField(blank=True, default=None, help_text='Print the letter on both sides (recto verso)', null=True, verbose_name='Duplex printing'),
        ),
        migrations.AddField(
            model_name='missivecampaign',
            name='color_printing_letter',
            field=models.BooleanField(default=False, help_text='Print the letter in color', verbose_name='Color printing'),
        ),
        migrations.AddField(
            model_name='missivecampaign',
            name='duplex_printing_letter',
            field=models.BooleanField(default=True, help_text='Print the letter on both sides (recto verso)', verbose_name='Duplex printing'),
        ),
    ]
