# Generated by Django 5.2.15 on 2026-09-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_pymissive', '0027_missive_letter_printing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missiverecipient',
            name='recipient_type',
            field=models.CharField(choices=[('recipient', 'Recipient'), ('cc', 'CC'), ('bcc', 'BCC'), ('notification', 'Notification')], default='recipient', help_text='Type of recipient (recipient, cc, bcc, notification)', max_length=20, verbose_name='Recipient Type'),
        ),
    ]
