# Generated by Django 5.2.15 on 2026-09-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_pymissive', '0028_missive_recipient_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missive',
            name='color_printing',
            field=models.BooleanField(default=False, help_text='Print the letter in color', verbose_name='Color printing'),
        ),
        migrations.AlterField(
            model_name='missive',
            name='duplex_printing',
            field=models.BooleanField(default=True, help_text='Print the letter on both sides (recto verso)', verbose_name='Duplex printing'),
        ),
    ]
