# Generated by Django 5.2.17 on 2026-10-06 14:09

import django_pymissive.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_pymissive', '0030_campaign_named_id_and_registered_printing'),
    ]

    operations = [
        migrations.AddField(
            model_name='missive',
            name='tags',
            field=django_pymissive.fields.JSONField(blank=True, default=list, help_text='Tags sent to the provider', verbose_name='Tags'),
        ),
    ]
