"""
Generate translation_catalog.py from pymissive.config.

Strings in pymissive.config are used via variables in django_pymissive.models.choices,
so xgettext (makemessages) cannot extract them. This command generates a Python module
with explicit _("literal") calls so makemessages can find them.

Run before makemessages:
  ./manage.py update_translation_catalog
  ./manage.py makemessages -l fr
"""

from pathlib import Path

from django.core.management.base import BaseCommand


def extract_strings_from_config() -> set[str]:
    """Extract all user-facing strings from pymissive.config."""
    from pymissive.config import (
        MISSIVE_ACKNOWLEDGEMENT_LEVELS,
        MISSIVE_TYPES,
        MISSIVE_EVENT_SUCCESS,
        MISSIVE_EVENT_INFO,
        MISSIVE_EVENT_FAILED,
        MISSIVE_DELIVERY_MODES,
        MISSIVE_PRIORITIES,
        MISSIVE_GENERIC_SUPPORT,
    )

    strings: set[str] = set()

    for level in MISSIVE_ACKNOWLEDGEMENT_LEVELS:
        strings.add(level["display_name"])
        if level.get("description"):
            strings.add(level["description"])
        if level.get("legal_value"):
            strings.add(level["legal_value"])
        for m in level.get("means") or []:
            strings.add(m)

    for v in MISSIVE_TYPES.values():
        strings.add(v)

    for v in MISSIVE_EVENT_SUCCESS.values():
        strings.add(v)
    for v in MISSIVE_EVENT_INFO.values():
        strings.add(v)
    for v in MISSIVE_EVENT_FAILED.values():
        strings.add(v)

    for k in MISSIVE_DELIVERY_MODES:
        strings.add(k.capitalize())

    for k in MISSIVE_PRIORITIES:
        strings.add(k.capitalize())

    for k in MISSIVE_GENERIC_SUPPORT.keys():
        strings.add(k.capitalize())

    return strings


def generate_catalog_content(strings: set[str]) -> str:
    """Generate translation_catalog.py source."""
    sorted_strings = sorted(strings, key=lambda s: (s.lower(), s))

    lines = [
        '"""',
        "Translation catalog for pymissive.config strings.",
        "",
        "Auto-generated by: ./manage.py update_translation_catalog",
        "Do not edit manually. Run update_translation_catalog after config changes.",
        '"""',
        "",
        "from django.utils.translation import gettext_lazy as _",
        "",
        "# Strings from pymissive.config - used by makemessages for extraction",
        "",
    ]

    for s in sorted_strings:
        # Escape backslash and quote for Python string literal
        escaped = s.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'_("{escaped}")')

    return "\n".join(lines) + "\n"


class Command(BaseCommand):
    help = "Generate translation_catalog.py from pymissive.config for makemessages extraction"

    def handle(self, *args, **options):
        strings = extract_strings_from_config()
        content = generate_catalog_content(strings)

        package_dir = Path(__file__).resolve().parent.parent.parent
        output_path = package_dir / "translation_catalog.py"

        output_path.write_text(content, encoding="utf-8")

        self.stdout.write(
            self.style.SUCCESS(
                f"Generated {output_path} with {len(strings)} translatable strings."
            )
        )
        self.stdout.write(
            "Run: ./manage.py makemessages -l fr"
        )
